name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        mcVersionIndex: ["1.8", "1.9", "1.10", "1.11", "1.11.2", "1.12", "1.13", "1.14", "1.15", "1.16", "1.16.5"]
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jre
    - run: npm install
    - name: Use Dumper
      run: node bin/dumpPackets -v ${{ matrix.mcVersionIndex }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packets
        path: output
    
  make-pr-comment:
    if: github.ref != 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: actions/download-artifact@v2
      with:
        name: packets
        path: packets
    - run: npm i -g minecraft-data
    - run: cd packets && node .github/workflows/md-comment-maker.js
    - id: get-comment-body
      run: |
          body=$(cat packets/README.md)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo ::set-output name=body::$body
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.get-comment-body.outputs.body }}
        reactions: rocket
    