name: PR-WORKFLOW

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  save-pr-number:
    runs-on: ubuntu-latest
    steps:
    - name: make directory
      run: mkdir output
    - name: Save PR number
      run: echo ${{ github.event.number }} > ./output/NR
    - name: save to artifact
      uses: actions/upload-artifact@v2
      with:
        name: packets
        path: output
  
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        mcVersionIndex: ['1.8.8', '1.9.4', '1.10.2', '1.11.2', '1.12.2', '1.13.2', '1.14.4', '1.15.2', '1.16.5', '1.17.1', '1.18.2', '1.19', '1.19.2', '1.19.3', '1.19.4', '1.20.1']
      fail-fast: false
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 17
        java-package: jre
    - run: npm install
    - name: Use Dumper
      run: |
        mkdir output
        node bin/dumpPackets -v ${{ matrix.mcVersionIndex }} -o output/${{ matrix.mcVersionIndex }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packets
        path: output
    
