name: PR-WORKFLOW

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  save-pr-number:
    runs-on: ubuntu-latest
    steps:
    - name: make directory
      run: mkdir output
    - name: Save PR number
      run: echo ${{ github.event.number }} > ./output/NR
    - name: save to artifact
      uses: actions/upload-artifact@v2
      with:
        name: packets
        path: output
  
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        mcVersionIndex: ["1.8", "1.9", "1.10", "1.11", "1.11.2", "1.12", "1.13", "1.14", "1.15", "1.16", "1.16.5"]
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jre
    - run: npm install
    - name: Use Dumper
      run: |
        mkdir output
        node bin/dumpPackets -v ${{ matrix.mcVersionIndex }} -o output/${{ matrix.mcVersionIndex }}
        rm -rf output/*/from-server/*
        rmdir output/*/from-server/*
        rm -rf output/*/README.md
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packets
        path: output

  make-diffs:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        mcVersionIndex: ["1.8", "1.9", "1.10", "1.11", "1.11.2", "1.12", "1.13", "1.14", "1.15", "1.16", "1.16.5"]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/download-artifact@v2
      with:
        name: packets
        path: packetsDumped
    - run: npm install -g json-diff
    - run: ls -R
    - name: Generate Diff
      run: |
        mkdir output
        json-diff bench/${{ matrix.mcVersionIndex }}/metadata/packets_info.json packetsDumped/${{ matrix.mcVersionIndex }}/metadata/packets_info.json > output/${{ matrix.mcVersionIndex }}.diff || true
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: diffs
        path: output   
